# Generated by Django 5.0.6 on 2024-06-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('es_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mi Usuario',
                'verbose_name_plural': 'Mis Usuarios',
            },
        ),
    ]
